---
- name: Install Docker
  hosts: prod
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes