apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod-ns
  labels:
    name: frontend
  namespace: team-a
spec:
  containers:
  - name: myfirstpodcontainer
    image: psrv3/example:13
    ports:
    - containerPort: 5000
