apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdeployment
  labels:
    app: myflaskapp
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myfirstpod
        image: psrv3/example:13
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myflaskapp
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstpodsvc
spec:
  selector:
    app: myflaskapp
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer


# kubectl autoscale deployment myfirstdeployment --cpu-percent=30 --min=1 --max=5
