apiVersion: v1
kind: Pod
metadata:
  name: customerb-pod
spec:
  containers:
  - name: customerb
    image: nginx
  tolerations:
  - key: "customer_name"
    operator: "Equal"
    value: "customer_B"
    effect: "NoSchedule"
