version: "3.9"
services:
  flaskcontainer:
    image: "psrv3/flaskappwithredis"
    ports:
      - "5001:5001"
  redis:
    image: "redis:alpine"

# docker build -t flaskcontainer .
# docker run -it -p 5001:5001 flaskcontainer