apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment-canary
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: canary
  template:
    metadata:
      labels:
        app: flask-app
        version: canary
    spec:
      containers:
      - name: flask-app
        image: psrv3/cicdbatchfifteenga:10
        ports:
        - containerPort: 5000