apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment-blue
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: blue
  template:
    metadata:
      labels:
        app: flask-app
        version: blue
    spec:
      containers:
      - name: flask-app
        image: psrv3/k8sapp:2
        ports:
        - containerPort: 5001
