apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
    version: green
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
