apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod
  namespace: default
spec:
  serviceAccountName: config-reader
  containers:
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "cat /etc/config/my-config-file"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap
