apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-reader-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: config-reader
  namespace: default
roleRef:
  kind: Role
  name: config-reader-role
  apiGroup: rbac.authorization.k8s.io
