apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    name: mynginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node_title
            operator: NotIn
            values:
            - "frontend"
  containers:
  - name: mynginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

#kubectl label nodes <node-name> node_title=frontend
#kubectl get nodes --show-labels
#kubectl describe pod <pod-name>


