#kubectl taint nodes node1 app=blue:NoSchedule


apiVersion: v1
kind: Pod
metadata:
  name: green-app
spec:
  containers:
  - name: green-app-container
    image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "green"
    effect: "NoSchedule"

#kubectl apply -f blue-app.yaml
#kubectl describe pod blue-app
#kubectl taint nodes node1 app-:NoSchedule/PreferNoSchedule/NoExecute
