apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: myflaskapp
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: flask-container
    image: psrv3/multicontainerps
    volumeMounts:
    - name: shared-data
      mountPath: /app/templates

  - name: ubuntu-container
    image: ubuntu
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello, World!!! > /pod-data/ubuntu.html"]